December 3, 2018 7:40:29 PM PST[ibm.cte.mq.jms.JMSItemConsumer.main()] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:217)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:156)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1859)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1708)
                               : com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.receiveAndLock(WMQSyncConsumerShadow.java:635)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.lockMessage(WMQMessageConsumer.java:870)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl._receiveBodyLock(JmsConsumerImpl.java:448)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl.receiveBody(JmsConsumerImpl.java:292)
                               : ibm.cte.mq.jms.JMSItemConsumer.run(JMSItemConsumer.java:60)
                               : ibm.cte.mq.jms.JMSItemConsumer.main(JMSItemConsumer.java:29)
                               : sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
                               : sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                               : sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                               : java.lang.reflect.Method.invoke(Method.java:498)
                               : org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
                               : java.lang.Thread.run(Thread.java:748)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:217)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:156)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1859)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1708)
                               : com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.receiveAndLock(WMQSyncConsumerShadow.java:635)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.lockMessage(WMQMessageConsumer.java:870)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl._receiveBodyLock(JmsConsumerImpl.java:448)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl.receiveBody(JmsConsumerImpl.java:292)
                               : ibm.cte.mq.jms.JMSItemConsumer.run(JMSItemConsumer.java:60)
                               : ibm.cte.mq.jms.JMSItemConsumer.main(JMSItemConsumer.java:29)
                               : sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
                               : sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                               : sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                               : java.lang.reflect.Method.invoke(Method.java:498)
                               : org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
                               : java.lang.Thread.run(Thread.java:748)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
December 3, 2018 7:40:44 PM PST[Finalizer] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQSession.disconnect(WMQSession.java:829)
                               : com.ibm.msg.client.wmq.internal.WMQSession.close(WMQSession.java:780)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:643)
                               : com.ibm.msg.client.jms.internal.JmsConnectionImpl.close(JmsConnectionImpl.java:497)
                               : com.ibm.msg.client.jms.internal.JmsConnectionImpl.finalize(JmsConnectionImpl.java:346)
                               : java.lang.System$2.invokeFinalize(System.java:1270)
                               : java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
                               : java.lang.ref.Finalizer.access$100(Finalizer.java:34)
                               : java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQSession.disconnect(WMQSession.java:829)
                               : com.ibm.msg.client.wmq.internal.WMQSession.close(WMQSession.java:780)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:643)
                               : com.ibm.msg.client.jms.internal.JmsConnectionImpl.close(JmsConnectionImpl.java:497)
                               : com.ibm.msg.client.jms.internal.JmsConnectionImpl.finalize(JmsConnectionImpl.java:346)
                               : java.lang.System$2.invokeFinalize(System.java:1270)
                               : java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
                               : java.lang.ref.Finalizer.access$100(Finalizer.java:34)
                               : java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)
     Caused by [2] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteSession.getConnection(RemoteSession.java:498)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1411)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1381)
                               : com.ibm.mq.jmqi.remote.api.RemoteFAP.MQDISC(RemoteFAP.java:2981)
                               : com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.MQDISC(InterceptedJmqiImpl.java:427)
                               : com.ibm.mq.ese.jmqi.ESEJMQI.MQDISC(ESEJMQI.java:396)
                               : com.ibm.msg.client.wmq.internal.WMQSession.disconnect(WMQSession.java:817)
                               : com.ibm.msg.client.wmq.internal.WMQSession.close(WMQSession.java:780)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:643)
                               : com.ibm.msg.client.jms.internal.JmsConnectionImpl.close(JmsConnectionImpl.java:497)
                               : com.ibm.msg.client.jms.internal.JmsConnectionImpl.finalize(JmsConnectionImpl.java:346)
                               : java.lang.System$2.invokeFinalize(System.java:1270)
                               : java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
                               : java.lang.ref.Finalizer.access$100(Finalizer.java:34)
                               : java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)
     Caused by [3] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3663)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:547)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
     Caused by [4] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'localhost/127.0.0.1:1414 (localhost)'. [1=-1,2=ffffffff,3=localhost/127.0.0.1:1414 (localhost),4=TCP]
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:758)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:699)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:139)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
